version:                     '3'
services:
  mariadb:
    image:                   mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    restart:                 always
    volumes:
     - ./mariadb:/var/lib/mysql

  backend:
    build:                   backend/
    command:                 node index.js
    working_dir:             /app/
    restart:                 always
    ports:
      - "8080:80"
